export interface DropdownItem {
  label: string;
  value: string;
}

export const Email: DropdownItem[] = [
  { label: 'gmail.com', value: 'gmail.com' },
  { label: 'naver.com', value: 'naver.com' },
  { label: 'icloud.com', value: 'icloud.com' },
  { label: 'kakao.com', value: 'kakao.com' },
  { label: 'daum.net', value: 'daum.net' },
  { label: 'hanmail.net', value: 'hanmail.net' },
];

//임시
export const Country:DropdownItem[]= [
  { label: '중국', value: '1' },
  { label: '베트남', value: '2' },
  { label: '태국', value: '3' },
  { label: '미국', value: '4' },
  { label: '우주베키스탄', value: '5' },
  { label: '네팔', value: '6' },
  { label: '인도네시아', value: '7' },
  { label: '러시아', value: '8' },
  { label: '필리핀', value: '9' },
  { label: '캄보디아', value: '10' },
  { label: '몽골', value: '11' },
  { label: '일본', value: '12' },
  { label: '미얀마', value: '13' },
  { label: '카자흐스탄', value: '14' },
  { label: '타이완', value: '15' },
  { label: '스리랑카', value: '16' },
  { label: '방글라데시', value: '17' },
  { label: '캐나다', value: '18' },
  { label: '파키스탄', value: '19' },
  { label: '인도', value: '20' },
  { label: '말레이시아', value: '21' },
  { label: '오스트레일리아', value: '22' },
  { label: '라오스', value: '23' },
  { label: '키르기스스탄', value: '24' },
  { label: '프랑스', value: '25' },
  { label: '싱가포르', value: '26' },
  { label: '홍콩', value: '27' },
  { label: '독일', value: '28' },
  { label: '영국', value: '29' },
  { label: '튀르키예', value: '30' },
  { label: '우크라이나', value: '31' },
  { label: '남아프리카 공화국', value: '32' },
  { label: '뉴질랜드', value: '33' },
  { label: '동티모르', value: '34' },
  { label: '브라질', value: '35' },
  { label: '이집트', value: '36' },
  { label: '이탈리아', value: '37' },
  { label: '나이지리아', value: '38' },
  { label: '타지키스탄', value: '39' },
  { label: '스페인', value: '40' },
  { label: '넥시코', value: '41' },
  { label: '이란', value: '42' },
  { label: '네덜란드', value: '43' },
  { label: '시리아', value: '44' },
  { label: '모로코', value: '45' },
  { label: '폴란드', value: '46' },
  { label: '가나', value: '47' },
  { label: '사우디아라비아', value: '48' },
  { label: '에티오피아', value: '49' },
  { label: '스웨덴', value: '50' },
  { label: '스위스', value: '51' },
  { label: '예멘', value: '52' },
  { label: '투르크메니스탄', value: '53' },
  { label: '콜롬비아', value: '54' },
  { label: '벨기에', value: '55' },
  { label: '페루', value: '56' },
  { label: '이스라엘', value: '57' },
  { label: '리비아', value: '58' },
  { label: '아프가니스탄', value: '59' },
  { label: '아일랜드', value: '60' },
]